"""
Research Agent: Handles external research and general knowledge queries.
Can be extended with web search capabilities.
"""

import logging
from typing import Dict, Any

logger = logging.getLogger(__name__)


class ResearchAgent:
    """
    Performs external research and provides general knowledge answers.
    Can be extended with web search APIs.
    """

    def __init__(self, search_provider: str = "none"):
        """
        Initialize research agent.

        Args:
            search_provider: Type of search provider (none, google, serper, etc.)
        """
        self.search_provider = search_provider
        self.logger = logger

    def research(self, query: str) -> Dict[str, Any]:
        """
        Conduct research on a topic.

        Args:
            query: Research query

        Returns:
            Research findings
        """
        if self.search_provider == "none":
            return self._research_knowledge_base(query)
        else:
            return self._research_web(query)

    def _research_knowledge_base(self, query: str) -> Dict[str, Any]:
        """
        Research using local knowledge base (for demo/offline mode).

        Args:
            query: Research query

        Returns:
            Research findings
        """
        query_lower = query.lower()

        # Simple knowledge base for common business questions
        knowledge_base = {
            "profit margin": {
                "findings": "Profit margin is a profitability metric calculated by dividing net income by revenue and multiplying by 100. It shows what percentage of revenue is profit. Higher margins indicate more efficient operations.",
                "calculation": "Profit Margin = (Profit / Revenue) × 100"
            },
            "sales performance": {
                "findings": "Sales performance metrics track revenue generation, growth rates, and product/region effectiveness. Key metrics include total sales, growth rate, top products, and sales by category.",
                "metrics": ["Total Revenue", "Growth Rate", "Top Products", "Sales by Region"]
            },
            "market trend": {
                "findings": "Market trends reflect changes in consumer behavior, pricing, demand, and competition in an industry.",
                "factors": ["Consumer demand", "Pricing changes", "Competitor activity", "Economic factors"]
            },
            "roi": {
                "findings": "Return on Investment (ROI) measures the profitability of an investment relative to its cost. ROI = (Gain - Cost) / Cost × 100",
                "interpretation": "Higher ROI indicates more efficient use of capital"
            },
            "revenue": {
                "findings": "Revenue is the total income generated by the sale of goods or services related to the company's primary operations.",
                "calculation": "Revenue = Price × Quantity Sold"
            }
        }

        # Search knowledge base
        for key, value in knowledge_base.items():
            if key in query_lower:
                return {
                    "success": True,
                    "findings": value.get("findings", ""),
                    "source": "Local Knowledge Base",
                    "type": "knowledge"
                }

        # Default response
        return {
            "success": False,
            "error": f"No research data available for '{query}'",
            "suggestion": "Try questions about business concepts like profit margin, ROI, revenue, market trends, etc."
        }

    def _research_web(self, query: str) -> Dict[str, Any]:
        """
        Research using web search (requires API configuration).

        Args:
            query: Research query

        Returns:
            Research findings
        """
        # This would be implemented with actual web search API
        # For now, return information about setup
        return {
            "success": False,
            "error": f"Web search not configured",
            "message": "To enable web search, configure your search API key (Serper, Google Search, etc.)",
            "type": "web_search"
        }

    def get_common_business_metrics(self) -> Dict[str, str]:
        """Get explanations of common business metrics."""
        return {
            "Revenue": "Total income from sales",
            "Profit": "Revenue minus all expenses",
            "Profit Margin": "Profit divided by revenue, shown as percentage",
            "Loss": "When expenses exceed revenue",
            "ROI": "Return on Investment - measure of profitability",
            "AOV": "Average Order Value - average transaction amount",
            "Growth Rate": "Percentage increase in revenue over time",
            "Cost": "Expenses incurred in business operations",
            "COGS": "Cost of Goods Sold - direct production costs"
        }

    def explain_metric(self, metric: str) -> Dict[str, Any]:
        """
        Explain a specific business metric.

        Args:
            metric: Metric name

        Returns:
            Metric explanation
        """
        explanations = {
            "profit_margin": {
                "definition": "Percentage of revenue that is profit",
                "formula": "(Profit / Revenue) × 100",
                "interpretation": "Higher is better - shows efficiency",
                "good_range": "10-25% for most industries"
            },
            "aov": {
                "definition": "Average value of customer transactions",
                "formula": "Total Revenue / Number of Transactions",
                "interpretation": "Higher AOV means larger average purchases",
                "use_case": "Identify upsell opportunities"
            },
            "roi": {
                "definition": "Measure of profit from an investment",
                "formula": "(Gain - Cost) / Cost × 100",
                "interpretation": "Shows return relative to investment",
                "good_range": "20% or higher is generally good"
            }
        }

        metric_key = metric.lower().replace(" ", "_")

        if metric_key in explanations:
            return {
                "success": True,
                "metric": metric,
                "explanation": explanations[metric_key]
            }
        else:
            return {
                "success": False,
                "error": f"No explanation available for: {metric}"
            }


class ResearchTools:
    """Tools for research analysis."""

    @staticmethod
    def analyze_trend(data: list, metric_name: str = "Metric") -> Dict[str, Any]:
        """
        Analyze trend in data.

        Args:
            data: List of values
            metric_name: Name of the metric

        Returns:
            Trend analysis
        """
        if len(data) < 2:
            return {
                "success": False,
                "error": "Need at least 2 data points for trend analysis"
            }

        # Calculate trend
        first = data[0]
        last = data[-1]
        change = last - first
        percent_change = (change / first * 100) if first != 0 else 0

        trend_direction = "up" if change > 0 else "down" if change < 0 else "stable"

        return {
            "success": True,
            "metric": metric_name,
            "start_value": first,
            "end_value": last,
            "change": change,
            "percent_change": percent_change,
            "direction": trend_direction
        }

    @staticmethod
    def get_best_performing(data: dict) -> Dict[str, Any]:
        """
        Identify best performing item.

        Args:
            data: Dictionary of items and values

        Returns:
            Best performing item
        """
        if not data:
            return {
                "success": False,
                "error": "No data provided"
            }

        best_item = max(data.items(), key=lambda x: x[1])

        return {
            "success": True,
            "item": best_item[0],
            "value": best_item[1]
        }
